#### zeros() 
###### –   괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화

In [18]:
import numpy as np

# y = np.zeros(shape=(10,2), dtype=np.int8)
y = np.zeros(10)
y

# x = np.array([1,2,3])
# type(x)
# x.shape


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### mean() : 배열에 저장된 원소들의 평균값을 계산


In [23]:
import numpy as np

list_1 = [1,2,3]
x = np.array(list_1)
np.mean(x)
x.mean()
x.shape

(3,)

#### array() Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력

In [35]:
x = np.array([1,2,3, 3])
y = np.array((1,2,3))
z = np.array({12,3,4})
a = np.array({"a":"b","a":"c" })
print(x,y, z ,a)

[1 2 3 3] [1 2 3] {3, 12, 4} {'a': 'c'}


##### reshape() 배열을 원하는 모양으로 생성

In [43]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b , b.shape ,'\n',c , c.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4) 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


##### reshape() 3차원  배열 만들기

In [50]:
a = np.arange(1,9)
print(a)
b = a.reshape(2,2,2)
print(b)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
a = np.arange(1,13)
print(a)
b = a.reshape(3,2,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


##### reshape 의미

###### reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며, 현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [57]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [59]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

##### ones()

In [71]:
y = np.ones([4,3])
# z = y*0.3
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### Numpy 배열의 슬라이싱 

In [77]:
list1  = [[1,11],[2,12],[3,13],[4,14] ]
print(list1[:][1])
print(list1[: , 1])

[2, 12]


TypeError: list indices must be integers or slices, not tuple

In [85]:
list1  = [[1,11],[2,12],[3,13],[4,14] ]
arr  = np.array(list1)
print(arr)
# print(arr[: , 1])
# print(arr [:][1])
# print(arr [1][1])
print(arr[1:3][1])
print(arr[1:4])


[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]
[ 3 13]
[[ 2 12]
 [ 3 13]
 [ 4 14]]


##### math 모듈의 sqrt() 와 numpy 모듈의 sqrt() 비교

In [89]:
import math
math.sqrt(2)
math.sqrt([2,3,4])

TypeError: must be real number, not list

In [94]:
import numpy as np 
np.sqrt(2)
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [97]:
import numpy as np

x = np.zeros(15)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [102]:
y = np.zeros([5,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [111]:
#(3,5)형태로 reshape
y = np.zeros([5,3])
z = y.reshape([3,5])
z += 4
print(z)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


###  전치행렬
###### transpose() –   행과 열을 교환하여 얻어지는 행렬 –행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미

In [114]:
import numpy as np

ary = np.array([[1,2],[3,4]])
print(ary)
print('\n\n\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2]
 [3 4]]




[[1 3]
 [2 4]]


In [115]:
ary = np.array([[1,2,5],[3,4,6]])
print(ary)
print('\n\n\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2 5]
 [3 4 6]]




[[1 3]
 [2 4]
 [5 6]]


##### 2개  배열에  대한  연산
###### –2개 배열에 저장된 내용을 인덱스별로 계산 
###### –선형대수학의 사칙연산과 동일하게 작동 –   곱셈도 같은 원리로 동작

In [122]:
import numpy as np

x = np.array((3,4,5))
y = np.array((1,2,3))
print(x+y)
print(x*y)
print(x%y)
print(x**y)

[4 6 8]
[ 3  8 15]
[0 0 2]
[  3  16 125]


In [130]:
x = np.array((3,4,5))
x **= 5
x += 6
print(x)

[ 249 1030 3131]


##### 인덱싱

In [131]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:,1])

[4 5 6]
[2 5 8]


##### 2개의  Numpy 배열  간의  계산

In [132]:
# x의 1행과 y의 3행을 더한 값을 출력한다.
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[0,:]+y[2,:])

[ 9 11 13]


In [136]:
print(x[:,1]*y[2,:])

[16 45 80]


In [137]:
a = np.array([10,20 , 30 ,40 , 60])

b  = a >30
print(b)

[False False False  True  True]


###### random()

In [144]:
import numpy as np

ary = np.random.random(5)
print(ary)

[0.45670659 0.4983063  0.9149761  0.99425434 0.03155385]


In [186]:
#, (0, 1) 범위에서 균일한 분포
a = np.random.rand(5)
print(a)

b = np.random.rand(2, 3)
print(b , b.shape)

[0.69742877 0.45354268 0.7220556  0.86638233 0.97552151]
[[0.85580334 0.01171408 0.35997806]
 [0.72999056 0.17162968 0.52103661]] (2, 3)


In [155]:
a = np.random.randint(10, size=6)
print(a)

b = np.random.randint(2, 10, size=10)
print(b)

c = np.random.randint(1, 5, size=(5, 3))
print(c)

[2 8 5 3 7 2]
[5 5 3 5 4 9 9 7 8 4]
[[4 1 4]
 [4 1 1]
 [1 4 1]
 [3 3 3]
 [4 1 4]]


##### random.seed()

In [216]:
import numpy as np

np.random.seed(0)

print(np.random.rand(2, 3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [326]:
# np.random.seed(0)
a = np.random.rand(5)
b = np.random.rand(5)

print(a,b)
# print(a>0.12)
# print(np.all(a>0.12))
# # print(a)

[0.67063787 0.21038256 0.1289263  0.31542835 0.36371077] [0.57019677 0.43860151 0.98837384 0.10204481 0.20887676]


##### any() 와  all() 의 비교

In [323]:
c = np.random.rand(5)
print(a)
print(a>0.12)
print(np.all(a>0.12))

[0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
[False False  True  True  True]
False


In [284]:
a = np.random.rand(5)
print(a>0.9)
print(np.any(a>0.9))

[False False False False False]
False


#### linspace()

##### 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분 0과 12를 포함한 그 사이의 값들을 선형적으로 분배하여 모두 4개의 원소를 갖는 배열을 생성
##### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [340]:
np.linspace(0, 12, 4 )

array([ 0.,  4.,  8., 12.])

In [341]:
#retstep=True이면 샘플 간의 간격을 출력
np.linspace(2, 13, 5,retstep=True )

(array([ 2.  ,  4.75,  7.5 , 10.25, 13.  ]), 2.75)

In [342]:
#endpoint=False이면 마지막 값을 제외하고 샘플값을 만들어냄
np.linspace(2, 13, 5,endpoint=False )

array([ 2. ,  4.2,  6.4,  8.6, 10.8])